#!/usr/bin/ruby
require 'test/unit'
require '../shlParse'
require './constant_tests'
require './if_tests'
require './variable_tests'
require './function_tests'
require './class_tests'
require './math_tests'
require './logic_tests'
